x-airflow-common:
  &airflow-common
  build:
    context: .
    dockerfile: Dockerfile

  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: 10

    _PIP_ADDITIONAL_REQUIREMENTS: >
      confluent-kafka
      yfinance
      pandas
      boto3
      snowflake-connector-python
      minio
      prometheus-client

  volumes:
    - ./src/airflow/dags:/opt/airflow/dags
    - ./src/airflow/logs:/opt/airflow/logs
    - ./src/airflow/plugins:/opt/airflow/plugins
    - ./src/airflow/requirements:/opt/airflow/requirements
    - ./src/airflow/reports:/opt/airflow/reports
    - /var/run/docker.sock:/var/run/docker.sock

  depends_on:
    postgres:
      condition: service_healthy

  networks:
    - data-network

services:

  postgres:
    image: postgres:13
    container_name: postgres

    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

    ports:
      - "5433:5432"

    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

    restart: always

    networks:
      - data-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper

    ports:
      - "2181:2181"

    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

    volumes:
      - ./data/zookeeper/data:/var/lib/zookeeper/data
      - ./data/zookeeper/log:/var/lib/zookeeper/log

    restart: always

    networks:
      - data-network

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka

    depends_on:
      - zookeeper

    ports:
      - "9092:9092"
      - "29092:29092"

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

    volumes:
      - ./data/kafka:/var/lib/kafka/data

    restart: always

    networks:
      - data-network

  minio:
    image: minio/minio:latest
    container_name: minio

    command: server /data --console-address ":9001"

    ports:
      - "9000:9000"
      - "9001:9001"

    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

    volumes:
      - ./data/minio:/data

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

    restart: always

    networks:
      - data-network

  minio-mc:
    image: minio/mc:latest
    container_name: minio-mc

    depends_on:
      - minio

    entrypoint: >
      /bin/sh -c "
      sleep 15;
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/stock-market-data;
      /usr/bin/mc anonymous set public myminio/stock-market-data;
      exit 0;
      "

    restart: on-failure

    networks:
      - data-network

  spark-master:
    image: apache/spark:3.5.1
    container_name: spark-master

    ports:
      - "8080:8080"
      - "7077:7077"

    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master

    volumes:
      - ./src/spark/jobs:/opt/spark/jobs
      - ./data/spark:/opt/spark/data

    restart: always

    networks:
      - data-network

  spark-worker:
    image: apache/spark:3.5.1
    container_name: spark-worker

    depends_on:
      - spark-master

    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077

    volumes:
      - ./src/spark/jobs:/opt/spark/jobs
      - ./data/spark:/opt/spark/data

    restart: always

    networks:
      - data-network

  spark-client:
    image: apache/spark:3.5.1
    container_name: spark-client

    depends_on:
      - spark-master

    command: sleep infinity

    volumes:
      - ./src/spark/jobs:/opt/spark/jobs
      - ./data:/opt/spark/data

    restart: always

    networks:
      - data-network

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init

    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
      --username airflow
      --password airflow
      --firstname admin
      --lastname admin
      --role Admin
      --email admin@example.com
      "

    environment:
      <<: *airflow-common-env

    restart: on-failure

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver

    command: webserver

    ports:
      - "8081:8080"

    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5

    restart: always

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler

    command: scheduler

    restart: always

networks:
  data-network:

volumes:
  postgres-db-volume:
